// <auto-generated />
namespace NguyenHuuBang_2080600938.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addIsCanceledColumnToCourseTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addIsCanceledColumnToCourseTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202303271000202_addIsCanceledColumnToCourseTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
